version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
  mongodb:
    build: ./mongodb
    image: kogito/debezium/mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=debezium
      - MONGODB_PASSWORD=dbz
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
    links:
      - kafka
      - mongodb
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
  sidecar:
    build: ./sidecar
    image: kogito/debezium/sidecar
    depends_on:
      - mongodb
      - connect
    environment:
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_PORT=27017
      - CONNECT_HOSTNAME=connect
      - CONNECT_PORT=8083
  kogito:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: kogito
    ports:
      - 8080:8080
    links:
      - mongodb
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - QUARKUS_MONGODB_CREDENTIALS_USERNAME=debezium
      - QUARKUS_MONGODB_CREDENTIALS_PASSWORD=dbz
      - QUARKUS_MONGODB_CREDENTIALS_AUTH-SOURCE=admin